#!/usr/bin/env bash
# UNRAID: build a tiny stand-in for an Unraid release zip, for development only.
#
# A real release is ~1.1 GB, so a full download/extract cycle makes iterating on
# the write path slow. This produces a zip with the same *shape* — the files
# unraid_postwrite.cpp patches, plus enough of the boot layout to be recognisable
# — in a few hundred kilobytes, so a full write finishes in seconds.
#
# The result is NOT bootable and must never be handed to a user.
#
#   ./src/unraid/tools/make-dev-image.sh
#   UNRAID_DEV_IMAGE=$PWD/build/unraid-dev-image.zip open "build/Unraid USB Creator.app"
#
# The extra OS entry only appears while UNRAID_DEV_IMAGE is set.

set -euo pipefail

out="${1:-build/unraid-dev-image.zip}"
mkdir -p "$(dirname "$out")"
out="$(cd "$(dirname "$out")" && pwd)/$(basename "$out")"

stage="$(mktemp -d)"
trap 'rm -rf "$stage"' EXIT

mkdir -p "$stage/config" "$stage/EFI/BOOT"

# The two files the post-write step rewrites. Defaults mirror a stock release so
# that a run which configures nothing still produces a sane result.
cat > "$stage/config/ident.cfg" <<'EOF'
# Generated by make-dev-image.sh — development use only
NAME="Tower"
COMMENT="Media server"
EOF

cat > "$stage/config/network.cfg" <<'EOF'
# Generated by make-dev-image.sh — development use only
USE_DHCP="yes"
IPADDR=
NETMASK=
GATEWAY=
EOF

cat > "$stage/changes.txt" <<'EOF'
Development stand-in image. Not a real Unraid release and not bootable.
EOF

# Placeholder payload. Kept small but non-empty so the extract path moves a
# realistic number of files rather than a single tiny one.
for f in bzimage bzroot bzfirmware bzmodules; do
    head -c 65536 /dev/urandom > "$stage/$f"
    # Releases ship a .sha256 beside each payload file; keep the shape identical.
    if command -v shasum >/dev/null 2>&1; then
        (cd "$stage" && shasum -a 256 "$f" > "$f.sha256")
    else
        (cd "$stage" && sha256sum "$f" > "$f.sha256")
    fi
done

head -c 4096 /dev/urandom > "$stage/EFI/BOOT/bootx64.efi"

rm -f "$out"
if command -v zip >/dev/null 2>&1; then
    (cd "$stage" && zip -q -r "$out" .)
else
    python_bin="$(command -v python3 || command -v python)"
    "$python_bin" - "$stage" "$out" <<'PY'
from pathlib import Path
import sys
import zipfile

source = Path(sys.argv[1])
with zipfile.ZipFile(sys.argv[2], "w", compression=zipfile.ZIP_DEFLATED) as archive:
    for entry in sorted(source.rglob("*")):
        archive.write(entry, entry.relative_to(source))
PY
fi

echo "Wrote $out ($(du -h "$out" | cut -f1))"
echo
echo "Use it with:"
echo "  UNRAID_DEV_IMAGE=$out open 'build/Unraid USB Creator.app'"
