name: Build MacOS

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v3

      # Use Cmake < 4.0
      - name: Setup CMake 3.31
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.31.x"

      # Use Qt 5, not Qt 6
      - name: Install Qt 5
        run: |
          brew update
          brew install qt@5

      - name: Configure CMake
        run: cmake -S . -B ../build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_PREFIX_PATH="$(brew --prefix qt@5)"

      - name: Build
        run: cmake --build ../build --config ${{ env.BUILD_TYPE }}

      # Setup keychain and certificates for signing & unlock keychain
      - name: Setup Keychain and Certificates
        env:
          APPLE_BUILD_CERTIFICATE_BASE64: ${{ secrets.APPLE_BUILD_CERTIFICATE_BASE64 }}
          APPLE_BUILD_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_BUILD_CERTIFICATE_PASSWORD }}
          APPLE_KEYCHAIN_PASSWORD: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}
        run: |
          chmod +x ../scripts/setup-keychain-mac.sh
          ../scripts/setup-keychain-mac.sh

        # Code sign the .app with proper certificate
      - name: Code Sign .app
        env:
          APPLE_SIGNING_KEY_ID: ${{ secrets.APPLE_SIGNING_KEY_ID }}
          APPLE_KEYCHAIN_PASSWORD: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}
        run: |
          CAPP="../build/unraid-usb-creator.app"
          codesign --deep --force --verify --verbose --sign "$APPLE_SIGNING_KEY_ID" --options runtime "$CAPP"

      # Remove quarantine attribute
      - name: Remove quarantine attribute
        run: sudo xattr -rc ../build/unraid-usb-creator.app

      # 7) Install Homebrew create-dmg (shell‐script version)
      - name: Install create-dmg
        run: |
          brew update
          brew install create-dmg

      # 8) Package the signed .app into a DMG that has "drag to Applications"
      - name: Create DMG with drag-to-Applications UI
        run: |
          # Make sure there's a Releases/ folder in the repo root
          mkdir -p "${{ github.workspace }}/Releases"

          # Create a “drag-to-Applications” DMG:
          create-dmg \
            --volname "Unraid Installer" \
            --volicon "${{ github.workspace }}/src/icons/unraid.icns" \
            --background "${{ github.workspace }}/src/icons/UN-logotype-gradient.png" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon "unraid-usb-creator.app" 200 190 \
            --hide-extension "unraid-usb-creator.app" \
            --app-drop-link 600 185 \
            "${{ github.workspace }}/Releases/unraid-usb-creator.dmg" \
            "${{ github.workspace }}/build/unraid-usb-creator.app"

      # Notarize the DMG
      - name: Notarize DMG
        env:
          APPLE_EMAIL_ADDRESS: ${{ secrets.APPLE_EMAIL_ADDRESS }}
          APPLE_APP_PASSWORD: ${{ secrets.APPLE_APP_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          cd "${{ github.workspace }}/Releases"
          xcrun notarytool submit "unraid-usb-creator.dmg" --apple-id "$APPLE_EMAIL_ADDRESS" --password "$APPLE_APP_PASSWORD" --team-id "$APPLE_TEAM_ID" --wait
          xcrun stapler staple "unraid-usb-creator.dmg"

      - name: Upload Mac DMG
        uses: actions/upload-artifact@v4
        with:
          name: UnraidInstallerMacOS
          path: Releases/unraid-usb-creator.dmg
